"""Archive auditor — four duties: clear debt, constitution check, finalize, merge verify."""

from pathlib import Path

from bridge.core.git_util import (
    log_merges, log_authors_count, log_grep_feature,
    git_ref_of, diff_stat, run_git,
)


def is_feature_archived(root: Path, feature: str) -> bool:
    """Check if a feature already has an archive commit.

    Searches git log for commits containing 'specpowers.*<feature>'.
    """
    commits = log_grep_feature(root, feature)
    return len(commits) > 0


def merge_check_detect(root: Path, last_archive_ref: str | None) -> bool:
    """Detect if post-merge validation is needed.

    Checks two signals:
    1. Merge commits since last_archive_ref
    2. Multiple authors since last_archive_ref

    If last_archive_ref is empty, check the whole history.
    """
    since_ref = last_archive_ref if last_archive_ref else None

    # Signal 1: merge commits
    merges = log_merges(root, since_ref)
    if merges:
        return True

    # Signal 2: multiple authors
    author_count = log_authors_count(root, since_ref)
    if author_count > 1:
        return True

    return False


def write_stub(root: Path, mode: str, commit_hash: str, change_summary: str) -> None:
    """Write an archive stub file for fast mode.

    Stub contains: mode marker, commit hash, change scope description.
    Write to OpenSpec archive directory if it exists.
    """
    openspec_dir = root / "openspec"
    archive_dir = openspec_dir / "archive" if openspec_dir.exists() else root / ".specpowers" / "archive"

    archive_dir.mkdir(parents=True, exist_ok=True)

    stub_content = f"""# Archive Stub (Fast Mode)

- **Mode**: {mode}
- **Commit**: {commit_hash}
- **Change Scope**: {change_summary}

> This stub was generated by SpecPowers fast mode archive.
> No full OpenSpec delta merge was performed.
"""
    stub_path = archive_dir / f"stub-{commit_hash}.md"
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write(stub_content)


def change_summary_input(root: Path, base: str | None = None) -> str:
    """Generate git diff --stat as input for natural language summary.

    The agent uses this to produce a 3-5 sentence description.
    """
    return diff_stat(root, base)


def audit(root: Path, mode: str) -> dict:
    """Run the full four-duty archive audit.

    Returns audit result dict with status for each duty.
    """
    result = {
        "debt_cleared": True,
        "constitution_verified": True,
        "artifacts_finalized": True,
        "merge_checked": True,
        "issues": [],
    }

    # Duty 1: Clear debt (pending escalations from build)
    # Check audit.log for unresolved escalations
    audit_log = root / ".specpowers" / "audit.log"
    if audit_log.exists():
        with open(audit_log, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                import json
                try:
                    entry = json.loads(line)
                    if entry.get("gate", {}).get("result") == "escalate":
                        result["debt_cleared"] = False
                        result["issues"].append(f"Unresolved escalation: {entry}")
                except json.JSONDecodeError:
                    pass

    # Duty 2: Constitution evidence check
    constitution_path = root / "constitution.md"
    if not constitution_path.exists():
        result["constitution_verified"] = False
        result["issues"].append("constitution.md not found")

    # Duty 3: Check plan/spec artifacts
    plan_path = root / "plan.md"
    spec_path = root / "spec.md"
    if mode == "full":
        if not plan_path.exists() and not spec_path.exists():
            result["artifacts_finalized"] = False
            result["issues"].append("No plan.md or spec.md found for full mode archive")

    # Duty 4: Merge check is done by caller (merge_check_detect)

    return result
