"""Mode controller — fast mode judgment, confirmation, checklist management."""

from pathlib import Path

SMALL_SIGNALS = ["bugfix", "单文件", "无新场景", "纯配置", "纯文案", "纯重构"]


def build_confirm_prompt(req: str, is_small: bool, signals: list[str], confidence: str) -> str:
    """Build structured confirmation prompt for fast mode.

    Format: [理由：<signal>/...，置信度：<高/中/低>]
    """
    signal_str = "/".join(signals) if signals else "none"
    return f"[理由：{signal_str}，置信度：{confidence}]"


def parse_confirm(text: str) -> dict:
    """Parse user confirmation response.

    Returns:
        {"go_fast": bool, "run_brainstorm": bool, "tdd": bool}
    """
    text_lower = text.strip().lower()

    result = {
        "go_fast": False,
        "run_brainstorm": False,
        "tdd": False,
    }

    # Detect mode choice
    if any(w in text_lower for w in ["go_fast", "fast", "快速", "确认优化", "y"]):
        result["go_fast"] = True
    elif any(w in text_lower for w in ["brainstorm", "完整", "full"]):
        result["run_brainstorm"] = True

    # Detect TDD declaration
    if any(w in text_lower for w in ["tdd", "测试驱动"]):
        result["tdd"] = True

    return result


def gen_checklist(req: str, dialog: str) -> list[str]:
    """Generate a 3-5 item acceptance checklist.

    Returns item list. Agent builds actual items; this validates bounds.
    """
    # The actual items are generated by the agent in fast_mode.md.
    # This function is a placeholder for boundary validation.
    items = _extract_checklist_items(dialog)
    return items


def _extract_checklist_items(dialog: str) -> list[str]:
    """Extract checklist items from agent dialog (markdown list)."""
    items = []
    for line in dialog.split("\n"):
        line = line.strip()
        if line.startswith("- ") or line.startswith("* ") or line.startswith("1. "):
            item = line.lstrip("- *1234567890. ").strip()
            if item:
                items.append(item)
    return items


def validate_checklist(items: list[str]) -> tuple[bool, str]:
    """Validate checklist boundaries.

    Returns:
        (ok, hint) where ok=False means reject/workaround needed.
    """
    if len(items) < 3:
        return False, "Checklist too short: at least 3 items required."
    if len(items) > 5:
        return False, "Checklist too long (>5 items): consider upgrading to full pipeline."
    return True, ""


def mark_fallback(state_path: Path, state: dict) -> dict:
    """Mark fallback used and increment counter.

    Fallback is limited to 1 per state lifecycle.
    """
    if state.get("fallback_used", False):
        raise ValueError("Fallback already used in this lifecycle. Cannot fallback again.")

    if state.get("fallback_count", 0) >= 1:
        raise ValueError(
            f"Fallback count ({state.get('fallback_count')}) exceeds limit. "
            f"Re-run /specpowers.constitution to reset lifecycle."
        )

    state["fallback_used"] = True
    state["fallback_count"] = state.get("fallback_count", 0) + 1
    state["stage"] = "specify"
    state["mode"] = "full"

    from bridge.core.fs_state import save_state
    save_state(state_path.parent, state)

    return state
