"""OpenSpec adapter — scenario generation and archive delta operations."""

from pathlib import Path


def to_scenario(req: str, brief: str | None = None) -> str:
    """Generate OpenSpec scenario format text from a requirement.

    The agent uses this output to write spec.md.

    Args:
        req: The requirement text.
        brief: Optional brief.md content from brainstorm phase.

    Returns:
        Formatted scenario text in OpenSpec format.
    """
    lines = ["# Scenario\n"]
    lines.append(f"## Description\n\n{req}\n")

    if brief:
        lines.append(f"## Context (from brief.md)\n\n{brief}\n")

    lines.append("## Acceptance Criteria\n")
    lines.append("- [ ] TBD - define acceptance criteria\n")

    lines.append("## Technical Notes\n")
    lines.append("- TBD\n")

    return "\n".join(lines)


def archive_delta(root: Path) -> None:
    """Run OpenSpec archive --delta command.

    This calls the OpenSpec CLI via subprocess (safe parameter list).
    The agent handles this in the cognitive layer; this function just
    records the intent and validates prerequisites.

    Args:
        root: Project root directory.

    Raises:
        FatalError: If OpenSpec CLI is not available or delta merge fails.
    """
    import subprocess
    import sys

    # Check if openspec CLI exists
    openspec_path = root / "openspec"
    if not openspec_path.exists():
        print("⚠ OpenSpec directory not found. Skipping delta merge.", file=sys.stderr)
        return

    # Try running openspec CLI
    cmd = ["npx", "openspec", "archive", "--delta"]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True, text=True, timeout=60,
            cwd=str(root),
        )
        if result.returncode != 0:
            # Delta merge conflict — recoverable
            print(f"⚠ OpenSpec delta merge has issues:\n{result.stderr}", file=sys.stderr)
            print("Manual conflict resolution may be needed.", file=sys.stderr)
        else:
            print("OpenSpec archive delta completed.")
    except FileNotFoundError:
        print("⚠ npx/openspec not found. Skipping delta merge.", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("⚠ OpenSpec delta merge timed out.", file=sys.stderr)


def write_stub(root: Path, mode: str, commit_hash: str, change_summary: str) -> None:
    """Write archive stub file directly (without OpenSpec CLI).

    For fast mode archive: git commit + stub with mode marker,
    commit hash, and change scope description.
    """
    openspec_dir = root / "openspec"
    archive_dir = openspec_dir / "archive" if openspec_dir.exists() else root / ".specpowers" / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)

    stub_content = f"""# Archive Stub (Fast Mode)

- **Mode**: {mode}
- **Commit**: {commit_hash}
- **Change Scope**: {change_summary}

> This stub was generated by SpecPowers fast mode archive.
> No full OpenSpec delta merge was performed.
"""
    stub_path = archive_dir / f"stub-{commit_hash}.md"
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write(stub_content)

    print(f"Stub written to: {stub_path}")
