"""superpowers adapter — skill execution and brief persistence."""

from pathlib import Path


def run_skill(name: str, ctx: dict | None = None) -> None:
    """Trigger a superpowers skill via agent.

    The agent actually executes the skill (e.g., /brainstorming).
    This function validates parameters and records the intent.

    Args:
        name: Skill name (brainstorming, writing-plans, executing-plans, etc.)
        ctx: Optional context dict.
    """
    if ctx is None:
        ctx = {}

    valid_skills = {
        "brainstorming", "writing-plans", "executing-plans",
        "subagent-driven-development", "test-driven-development",
        "using-git-worktrees",
    }

    if name not in valid_skills:
        print(f"⚠ Unknown superpowers skill: {name}")
        print(f"  Valid skills: {', '.join(sorted(valid_skills))}")

    print(f"Superpowers skill '{name}' triggered.")
    if ctx:
        print(f"  Context: {ctx}")


def persist_brief(summary: str, root: Path) -> None:
    """Persist brainstorm summary to brief.md.

    The agent provides the structured summary; this function writes it to disk.
    No secondary extraction is performed.

    Args:
        summary: The structured decision summary from brainstorm.
        root: Project root directory.
    """
    brief_path = root / "brief.md"

    content = f"""# Feature Brief

{summary}

---
*Generated by SpecPowers brainstorm phase*
"""
    with open(brief_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"brief.md written to: {brief_path}")
